export const LOGIN_SELLER_REQUEST = "LOGIN_SELLER_REQUEST";
export const LOGIN_SELLER_SUCCESS = "LOGIN_SELLER_SUCCESS";
export const LOGIN_SELLER_FAILURE = "LOGIN_SELLER_FAILURE";

export const LOGOUT_SELLER_REQUEST = "LOGOUT_SELLER_REQUEST";
export const LOGOUT_SELLER_SUCCESS = "LOGOUT_SELLER_SUCCESS";
export const LOGOUT_SELLER_FAILURE = "LOGOUT_SELLER_FAILURE";

export const REGISTER_SELLER_REQUEST = "REGISTER_SELLER_REQUEST";
export const REGISTER_SELLER_SUCCESS = "REGISTER_SELLER_SUCCESS";
export const REGISTER_SELLER_FAILURE = "REGISTER_SELLER_FAILURE";

export const GET_UNAPPROVED_SELLER_PAGE_REQUEST="GET_UNAPPROVED_SELLER_PAGE_REQUEST";
export const GET_UNAPPROVED_SELLER_PAGE_SUCCESS="GET_UNAPPROVED_SELLER_PAGE_SUCCESS";
export const GET_UNAPPROVED_SELLER_PAGE_FAILURE="GET_UNAPPROVED_SELLER_PAGE_FAILURE";


export const GET_APPROVED_SELLER_PAGE_REQUEST="GET_APPROVED_SELLER_PAGE_REQUEST";
export const GET_APPROVED_SELLER_PAGE_SUCCESS="GET_APPROVED_SELLER_PAGE_SUCCESS";
export const GET_APPROVED_SELLER_PAGE_FAILURE="GET_APPROVED_SELLER_PAGE_FAILURE";



export const GET_SUSPENDED_SELLER_PAGE_REQUEST="GET_SUSPENDED_SELLER_PAGE_REQUEST";
export const GET_SUSPENDED_SELLER_PAGE_SUCCESS="GET_SUSPENDED_SELLER_PAGE_SUCCESS";
export const GET_SUSPENDED_SELLER_PAGE_FAILURE="GET_SUSPENDED_SELLER_PAGE_FAILURE";



export const GET_REJECTED_SELLER_PAGE_REQUEST="GET_REJECTED_SELLER_PAGE_REQUEST";
export const GET_REJECTED_SELLER_PAGE_SUCCESS="GET_REJECTED_SELLER_PAGE_SUCCESS";
export const GET_REJECTED_SELLER_PAGE_FAILURE="GET_REJECTED_SELLER_PAGE_FAILURE";

export const GET_SELLER_BY_ID_REQUEST="GET_SELLER_BY_ID_REQUEST";
export const GET_SELLER_BY_ID_SUCCESS="GET_SELLER_BY_ID_SUCCESS";
export const GET_SELLER_BY_ID_FAILURE="GET_SELLER_BY_ID_FAILURE";



export const APPROVE_SELLER_BY_ID_REQUEST="APPROVE_SELLER_BY_ID_REQUEST";
export const APPROVE_SELLER_BY_ID_SUCCESS="APPROVE_SELLER_BY_ID_SUCCESS";
export const APPROVE_SELLER_BY_ID_FAILURE="APPROVE_SELLER_BY_ID_FAILURE";


export const REJECT_SELLER_BY_ID_REQUEST="REJECT_SELLER_BY_ID_REQUEST";
export const REJECT_SELLER_BY_ID_SUCCESS="REJECT_SELLER_BY_ID_SUCCESS";
export const REJECT_SELLER_BY_ID_FAILURE="REJECT_SELLER_BY_ID_FAILURE";


export const GET_SELLER_PROFILE_REQUEST="GET_SELLER_PROFILE_REQUEST";
export const GET_SELLER_PROFILE_SUCCESS="GET_SELLER_PROFILE_SUCCESS";   
export const GET_SELLER_PROFILE_FAILURE="GET_SELLER_PROFILE_FAILURE";   


export const TOTAL_SELLER_COUNT_DATA_REQUEST="TOTAL_SELLER_COUNT_DATA_REQUEST";
export const TOTAL_SELLER_COUNT_DATA_SUCCESS="TOTAL_SELLER_COUNT_DATA_SUCCESS";
export const TOTAL_SELLER_COUNT_DATA_FAILURE="TOTAL_SELLER_COUNT_DATA_FAILURE";
