export const LOGIN_SELLER_REQUEST = "LOGIN_SELLER_REQUEST";
export const LOGIN_SELLER_SUCCESS = "LOGIN_SELLER_SUCCESS";
export const LOGIN_SELLER_FAILURE = "LOGIN_SELLER_FAILURE";

export const LOGOUT_SELLER_REQUEST = "LOGOUT_SELLER_REQUEST";
export const LOGOUT_SELLER_SUCCESS = "LOGOUT_SELLER_SUCCESS";
export const LOGOUT_SELLER_FAILURE = "LOGOUT_SELLER_FAILURE";

export const REGISTER_SELLER_REQUEST = "REGISTER_SELLER_REQUEST";
export const REGISTER_SELLER_SUCCESS = "REGISTER_SELLER_SUCCESS";
export const REGISTER_SELLER_FAILURE = "REGISTER_SELLER_FAILURE";