export const GET_SELLER_DETAILS_REQUEST = "GET_SELLER_DETAILS_REQUEST";
export const GET_SELLER_DETAILS_SUCCESS = "GET_SELLER_DETAILS_SUCCESS";
export const GET_SELLER_DETAILS_FAILURE = "GET_SELLER_DETAILS_FAILURE";

export const UPDATE_SELLER_REQUEST = "UPDATE_SELLER_REQUEST";
export const UPDATE_SELLER_SUCCESS = "UPDATE_SELLER_SUCCESS";
export const UPDATE_SELLER_FAILURE = "UPDATE_SELLER_FAILURE";

