export const LOGIN_SHOPS_REQUEST = "LOGIN_SHOPS_REQUEST";
export const LOGIN_SHOPS_SUCCESS = "LOGIN_SHOPS_SUCCESS";
export const LOGIN_SHOPS_FAILURE = "LOGIN_SHOPS_FAILURE";

export const LOGOUT_SHOPS_REQUEST = "LOGOUT_SHOPS_REQUEST";
export const LOGOUT_SHOPS_SUCCESS = "LOGOUT_SHOPS_SUCCESS";
export const LOGOUT_SHOPS_FAILURE = "LOGOUT_SHOPS_FAILURE";

export const REGISTER_SHOPS_REQUEST = "REGISTER_SHOPS_REQUEST";
export const REGISTER_SHOPS_SUCCESS = "REGISTER_SHOPS_SUCCESS";
export const REGISTER_SHOPS_FAILURE = "REGISTER_SHOPS_FAILURE";

export const GET_UNAPPROVED_SHOPS_PAGE_REQUEST="GET_UNAPPROVED_SHOPS_PAGE_REQUEST";
export const GET_UNAPPROVED_SHOPS_PAGE_SUCCESS="GET_UNAPPROVED_SHOPS_PAGE_SUCCESS";
export const GET_UNAPPROVED_SHOPS_PAGE_FAILURE="GET_UNAPPROVED_SHOPS_PAGE_FAILURE";


export const GET_APPROVED_SHOPS_PAGE_REQUEST="GET_APPROVED_SHOPS_PAGE_REQUEST";
export const GET_APPROVED_SHOPS_PAGE_SUCCESS="GET_APPROVED_SHOPS_PAGE_SUCCESS";
export const GET_APPROVED_SHOPS_PAGE_FAILURE="GET_APPROVED_SHOPS_PAGE_FAILURE";



export const GET_SUSPENDED_SHOPS_PAGE_REQUEST="GET_SUSPENDED_SHOPS_PAGE_REQUEST";
export const GET_SUSPENDED_SHOPS_PAGE_SUCCESS="GET_SUSPENDED_SHOPS_PAGE_SUCCESS";
export const GET_SUSPENDED_SHOPS_PAGE_FAILURE="GET_SUSPENDED_SHOPS_PAGE_FAILURE";



export const GET_REJECTED_SHOPS_PAGE_REQUEST="GET_REJECTED_SHOPS_PAGE_REQUEST";
export const GET_REJECTED_SHOPS_PAGE_SUCCESS="GET_REJECTED_SHOPS_PAGE_SUCCESS";
export const GET_REJECTED_SHOPS_PAGE_FAILURE="GET_REJECTED_SHOPS_PAGE_FAILURE";

export const GET_SHOPS_BY_ID_REQUEST="GET_SHOPS_BY_ID_REQUEST";
export const GET_SHOPS_BY_ID_SUCCESS="GET_SHOPS_BY_ID_SUCCESS";
export const GET_SHOPS_BY_ID_FAILURE="GET_SHOPS_BY_ID_FAILURE";



export const APPROVE_SHOPS_BY_ID_REQUEST="APPROVE_SHOPS_BY_ID_REQUEST";
export const APPROVE_SHOPS_BY_ID_SUCCESS="APPROVE_SHOPS_BY_ID_SUCCESS";
export const APPROVE_SHOPS_BY_ID_FAILURE="APPROVE_SHOPS_BY_ID_FAILURE";


export const REJECT_SHOPS_BY_ID_REQUEST="REJECT_SHOPS_BY_ID_REQUEST";
export const REJECT_SHOPS_BY_ID_SUCCESS="REJECT_SHOPS_BY_ID_SUCCESS";
export const REJECT_SHOPS_BY_ID_FAILURE="REJECT_SHOPS_BY_ID_FAILURE";


export const SUSPEND_SHOP_BY_ID_REQUEST="SUSPEND_SHOP_BY_ID_REQUEST";
export const SUSPEND_SHOP_BY_ID_SUCCESS="SUSPEND_SHOP_BY_ID_SUCCESS";
export const SUSPEND_SHOP_BY_ID_FAILURE="SUSPEND_SHOP_BY_ID_FAILURE";


export const GET_SHOPS_LIST_REQUEST="GET_SHOP_LIST_REQUEST";
export const GET_SHOPS_LIST_SUCCESS="GET_SHOP_LIST_SUCCESS";
export const GET_SHOPS_LIST_FAILURE="GET_SHOP_LIST_FAILURE";