export const GET_CART_COUNT_REQUEST="GET_CART_COUNT_REQUEST"
export const GET_CART_COUNT_SUCCESS="GET_CART_COUNT_SUCCESS"
export const GET_CART_COUNT_FAILURE="GET_CART_COUNT_FAILURE"

export const GET_CART_BY_ID_REQUEST="GET_CART_BY_ID_REQUEST"

export const GET_CART_BY_ID_SUCCESS="GET_CART_BY_ID_SUCCESS"

export const GET_CART_BY_ID_FAILURE="GET_CART_BY_ID_FAILURE"