export const CREATE_PRODUCTS_REQUEST="CREATE_PRODUCTS_REQUEST";
export const CREATE_PRODUCTS_SUCCESS="CREATE_PRODUCTS_SUCCESS";
export const CREATE_PRODUCTS_FAILURE="CREATE_PRODUCTS_FAILURE";

export const GET_PRODUCTS_REQUEST="GET_PRODUCTS_REQUEST";
export const GET_PRODUCTS_SUCCESS="GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAILURE="GET_PRODUCTS_FAILURE";

export const UPDATE_PRODUCTS_REQUEST="UPDATE_PRODUCTS_REQUEST";
export const UPDATE_PRODUCTS_SUCCESS="UPDATE_PRODUCTS_SUCCESS";
export const UPDATE_PRODUCTS_FAILURE="UPDATE_PRODUCTS_FAILURE";

export const DELETE_PRODUCTS_REQUEST="DELETE_PRODUCTS_REQUEST";
export const DELETE_PRODUCTS_SUCCESS="DELETE_PRODUCTS_SUCCESS";
export const DELETE_PRODUCTS_FAILURE="DELETE_PRODUCTS_FAILURE"; 

export const GET_CATEGORIES_REQUEST="GET_CATEGORIES_REQUEST";
export const GET_CATEGORIES_SUCCESS="GET_CATEGORIES_SUCCESS";
export const GET_CATEGORIES_FAILURE="GET_CATEGORIES_FAILURE";   
