export const GET_ORDERS_COUNT_REQUEST="GET_ORDERS_COUNT_REQUEST";
export const GET_ORDERS_COUNT_SUCCESS="GET_ORDERS_COUNT_SUCCESS";
export const GET_ORDERS_COUNT_FAILURE="GET_ORDERS_COUNT_FAILURE";

export const GET_PLACED_ORDERS_COUNT_REQUEST="GET_PLACED_ORDERS_COUNT_REQUEST";
export const GET_PLACED_ORDERS_COUNT_SUCCESS="GET_PLACED_ORDERS_COUNT_SUCCESS";
export const GET_PLACED_ORDERS_COUNT_FAILURE="GET_PLACED_ORDERS_COUNT_FAILURE";


